#!/bin/mksh

dunstctl close-all

update_vol () {
	vol="$(pactl list sinks | grep '^[[:space:]]Volume:' | \
	head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')"
}

update_vol

count=$(($vol + 2))
if [[ $1 -gt 0 ]]; then
	count=$(($vol + $1))
fi

for SINK in `pacmd list-sinks | grep 'index:' | cut -b12-`
do
    pacmd set-sink-volume $SINK "$((count*655))"
done

update_vol
notify-send "volume: $vol%"
